apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: laptop
servers: 1
kubeAPI:
  hostIP: "127.0.0.1"
ports:
  - port: 127.0.0.1:80:80
    nodeFilters:
      - loadbalancer
  - port: 127.0.0.1:443:443
    nodeFilters:
      - loadbalancer
network: laptop

options:
  k3d:
    wait: true
    timeout: "60s"
